baseURL = 'https://www.digitalwaehrung.ch/'
languageCode = 'de_CH'
title = 'DigitalWaehrung.ch - Your Comprehensive Guide to Stablecoins'

[module]
  [[module.imports]]
    path = 'github.com/imfing/hextra'
